services:
  faucet.webapp:
    image: faucet.webapp
    container_name: faucet.webapp
    hostname: faucet.webapp
    restart: always
    build:
      context: .
      dockerfile: Faucet.WebApp/Dockerfile
    env_file: ".env"
    # for mDNS support
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
