services:
  faucet.webapp:
    image: faucet.webapp
    container_name: faucet.webapp
    hostname: faucet.webapp
    restart: always
    build:
      context: .
      dockerfile: Faucet.WebApp/Dockerfile
    env_file: ".env"
